services:
  magnito:
    image: frourio/magnito:0.11.0
    ports:
      - 5050:5050
      - 5051:5051
    env_file:
      - ./client/.env
    volumes:
      - magnito:/usr/src/app/data

  inbucket:
    image: inbucket/inbucket:3.0.3
    ports:
      - 2500:2500 # SMTP
      - 2501:9000 # web interface
    volumes:
      - inbucket:/storage

  minio:
    image: minio/minio:RELEASE.2023-08-23T10-07-06Z
    ports:
      - 9000:9000 # Storage
      - 9001:9001 # Console
    env_file:
      - ./server/.env
    volumes:
      - minio:/data
    entrypoint: []
    command: minio server /data --address :9000 --console-address :9001
    healthcheck:
      test: bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      timeout: 5s
      interval: 5s

  mc:
    image: minio/mc:RELEASE.2023-08-18T21-57-55Z
    depends_on:
      minio:
        condition: service_healthy
    env_file:
      - ./server/.env
    entrypoint: []
    command: |
      sh -c "
        mc alias set myminio http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD
        mc mb myminio/$$S3_BUCKET --region=$$S3_REGION || true
        mc mb myminio/$$TEST_S3_BUCKET --region=$$S3_REGION || true
      "

  postgres:
    image: postgres:15.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
      TZ: Asia/Tokyo
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  magnito:
    driver: local
  inbucket:
    driver: local
  minio:
    driver: local
  postgres:
    driver: local
